baseURL = "https://puzzathlon.github.io"
languageCode = "en-us"
theme = "hello-friend"

title = "Puzzathlon"
homeSubtitle = "In Association with RHUL Computing Society"
contentTypeName = "content/problems"

